-- Trigger Definitions for ERP Payroll System
-- Version: 1.0
-- Database: PostgreSQL
-- Generated by: ERP System
-- Date: 2023-11-15

-- Trigger to generate messages when a payroll is approved
CREATE OR REPLACE FUNCTION create_payroll_notification()
RETURNS TRIGGER AS $$
DECLARE
    employee_first_name VARCHAR;
    institution_name VARCHAR := 'ERP System';
    month_year VARCHAR;
    amount NUMERIC(10, 2);
    employee_code VARCHAR;
    message_content TEXT;
BEGIN
    -- Only proceed if status is changing to 'PAID'
    IF NEW.status = 'PAID' AND (OLD.status IS NULL OR OLD.status <> 'PAID') THEN
        -- Get employee details
        SELECT e.first_name, e.code INTO employee_first_name, employee_code
        FROM employees e
        WHERE e.id = NEW.employee_id;

        -- Format month/year
        month_year := to_char(NEW.year_month, 'Month YYYY');

        -- Format amount
        amount := NEW.net_salary;

        -- Create message content
        message_content := 'Dear ' || employee_first_name || ', your Salary of ' || month_year || 
                          ' from ' || institution_name || ' (Amount: ' || amount || ') has been credited to your ' || 
                          employee_code || ' account successfully.';

        -- Insert message
        INSERT INTO messages (
            employee_id, 
            content, 
            year_month, 
            created_at, 
            status
        ) VALUES (
            NEW.employee_id,
            message_content,
            NEW.year_month,
            NOW(),
            'PENDING'
        );
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create the trigger on pay_slips table
DROP TRIGGER IF EXISTS payroll_notification_trigger ON pay_slips;
CREATE TRIGGER payroll_notification_trigger
AFTER UPDATE ON pay_slips
FOR EACH ROW
EXECUTE FUNCTION create_payroll_notification();
